import { chromium } from "playwright";
import { existsSync } from "node:fs";
const cam = "/opt/pw-browsers/chromium";
const b = await chromium.launch({ ...(existsSync(cam)?{executablePath:cam}:{}) , args:["--no-proxy-server"]});
const p = await (await b.newContext({viewport:{width:393,height:852}})).newPage();
const logs=[];
p.on("console",m=>logs.push(m.type()+": "+m.text().slice(0,180)));
p.on("pageerror",e=>logs.push("PAGEERROR: "+String(e).slice(0,180)));
await p.goto("http://127.0.0.1:8081/auth#access_token=abc&refresh_token=d&type=recovery",{waitUntil:"networkidle"});
await p.waitForTimeout(2500);
console.log("--- TEXTO ---");
console.log((await p.locator("main, body").first().innerText()).slice(0,700));
console.log("--- LOGS ---");
logs.filter(l=>/error|PAGEERROR|warn/i.test(l)).slice(0,6).forEach(l=>console.log(l));
await b.close();
