/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as TamanhoRealRouteImport } from './routes/tamanho-real'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as PrimeiraConsultaRouteImport } from './routes/primeira-consulta'
import { Route as PreviewSaudeRouteImport } from './routes/preview-saude'
import { Route as PreviewNotificacoesRouteImport } from './routes/preview-notificacoes'
import { Route as PreviewJogoRouteImport } from './routes/preview-jogo'
import { Route as PreviewHomeRouteImport } from './routes/preview-home'
import { Route as PreviewGradesRouteImport } from './routes/preview-grades'
import { Route as PreviewContaRouteImport } from './routes/preview-conta'
import { Route as PreviewChatRouteImport } from './routes/preview-chat'
import { Route as MuralRouteImport } from './routes/mural'
import { Route as ModoAcompanhanteRouteImport } from './routes/modo-acompanhante'
import { Route as MitosRouteImport } from './routes/mitos'
import { Route as MedicosRouteImport } from './routes/medicos'
import { Route as LivesRouteImport } from './routes/lives'
import { Route as HospitaisRouteImport } from './routes/hospitais'
import { Route as GestacaoRouteImport } from './routes/gestacao'
import { Route as ExperienciaRouteImport } from './routes/experiencia'
import { Route as EpdsRouteImport } from './routes/epds'
import { Route as EncontrarMedicoRouteImport } from './routes/encontrar-medico'
import { Route as EmpresasRouteImport } from './routes/empresas'
import { Route as DppRouteImport } from './routes/dpp'
import { Route as DiabetesGestacionalRouteImport } from './routes/diabetes-gestacional'
import { Route as DepoimentosRouteImport } from './routes/depoimentos'
import { Route as CardsRouteImport } from './routes/cards'
import { Route as CalculadoraRouteImport } from './routes/calculadora'
import { Route as BatimentosRouteImport } from './routes/batimentos'
import { Route as BastidoresRouteImport } from './routes/bastidores'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AgendamentoRouteImport } from './routes/agendamento'
import { Route as AcompanhanteRouteImport } from './routes/acompanhante'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VotarNomeTokenRouteImport } from './routes/votar-nome.$token'
import { Route as MedicosGoogleCallbackRouteImport } from './routes/medicos_.google-callback'
import { Route as MedicosCadastroRouteImport } from './routes/medicos_.cadastro'
import { Route as ApiWhatsappRouteImport } from './routes/api/whatsapp'
import { Route as ApiWaitlistTickRouteImport } from './routes/api/waitlist-tick'
import { Route as ApiTranscribeRouteImport } from './routes/api/transcribe'
import { Route as ApiStripeWebhookRouteImport } from './routes/api/stripe-webhook'
import { Route as ApiPushWeeklyTickRouteImport } from './routes/api/push-weekly-tick'
import { Route as ApiNutritionRouteImport } from './routes/api/nutrition'
import { Route as ApiMpWebhookRouteImport } from './routes/api/mp-webhook'
import { Route as ApiInstagramWebhookRouteImport } from './routes/api/instagram-webhook'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ApiCartaSemanalRouteImport } from './routes/api/carta-semanal'
import { Route as AlbumTokenRouteImport } from './routes/album.$token'
import { Route as AcompanharTokenRouteImport } from './routes/acompanhar.$token'
import { Route as AuthenticatedPainelRouteImport } from './routes/_authenticated/painel'
import { Route as AuthenticatedMinhaContaRouteImport } from './routes/_authenticated/minha-conta'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as ApiDoctorthinkTrainRouteImport } from './routes/api/doctorthink/train'
import { Route as ApiDoctorthinkAskRouteImport } from './routes/api/doctorthink/ask'

const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const TamanhoRealRoute = TamanhoRealRouteImport.update({
  id: '/tamanho-real',
  path: '/tamanho-real',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const PrimeiraConsultaRoute = PrimeiraConsultaRouteImport.update({
  id: '/primeira-consulta',
  path: '/primeira-consulta',
  getParentRoute: () => rootRouteImport,
} as any)
const PreviewSaudeRoute = PreviewSaudeRouteImport.update({
  id: '/preview-saude',
  path: '/preview-saude',
  getParentRoute: () => rootRouteImport,
} as any)
const PreviewNotificacoesRoute = PreviewNotificacoesRouteImport.update({
  id: '/preview-notificacoes',
  path: '/preview-notificacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const PreviewJogoRoute = PreviewJogoRouteImport.update({
  id: '/preview-jogo',
  path: '/preview-jogo',
  getParentRoute: () => rootRouteImport,
} as any)
const PreviewHomeRoute = PreviewHomeRouteImport.update({
  id: '/preview-home',
  path: '/preview-home',
  getParentRoute: () => rootRouteImport,
} as any)
const PreviewGradesRoute = PreviewGradesRouteImport.update({
  id: '/preview-grades',
  path: '/preview-grades',
  getParentRoute: () => rootRouteImport,
} as any)
const PreviewContaRoute = PreviewContaRouteImport.update({
  id: '/preview-conta',
  path: '/preview-conta',
  getParentRoute: () => rootRouteImport,
} as any)
const PreviewChatRoute = PreviewChatRouteImport.update({
  id: '/preview-chat',
  path: '/preview-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const MuralRoute = MuralRouteImport.update({
  id: '/mural',
  path: '/mural',
  getParentRoute: () => rootRouteImport,
} as any)
const ModoAcompanhanteRoute = ModoAcompanhanteRouteImport.update({
  id: '/modo-acompanhante',
  path: '/modo-acompanhante',
  getParentRoute: () => rootRouteImport,
} as any)
const MitosRoute = MitosRouteImport.update({
  id: '/mitos',
  path: '/mitos',
  getParentRoute: () => rootRouteImport,
} as any)
const MedicosRoute = MedicosRouteImport.update({
  id: '/medicos',
  path: '/medicos',
  getParentRoute: () => rootRouteImport,
} as any)
const LivesRoute = LivesRouteImport.update({
  id: '/lives',
  path: '/lives',
  getParentRoute: () => rootRouteImport,
} as any)
const HospitaisRoute = HospitaisRouteImport.update({
  id: '/hospitais',
  path: '/hospitais',
  getParentRoute: () => rootRouteImport,
} as any)
const GestacaoRoute = GestacaoRouteImport.update({
  id: '/gestacao',
  path: '/gestacao',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperienciaRoute = ExperienciaRouteImport.update({
  id: '/experiencia',
  path: '/experiencia',
  getParentRoute: () => rootRouteImport,
} as any)
const EpdsRoute = EpdsRouteImport.update({
  id: '/epds',
  path: '/epds',
  getParentRoute: () => rootRouteImport,
} as any)
const EncontrarMedicoRoute = EncontrarMedicoRouteImport.update({
  id: '/encontrar-medico',
  path: '/encontrar-medico',
  getParentRoute: () => rootRouteImport,
} as any)
const EmpresasRoute = EmpresasRouteImport.update({
  id: '/empresas',
  path: '/empresas',
  getParentRoute: () => rootRouteImport,
} as any)
const DppRoute = DppRouteImport.update({
  id: '/dpp',
  path: '/dpp',
  getParentRoute: () => rootRouteImport,
} as any)
const DiabetesGestacionalRoute = DiabetesGestacionalRouteImport.update({
  id: '/diabetes-gestacional',
  path: '/diabetes-gestacional',
  getParentRoute: () => rootRouteImport,
} as any)
const DepoimentosRoute = DepoimentosRouteImport.update({
  id: '/depoimentos',
  path: '/depoimentos',
  getParentRoute: () => rootRouteImport,
} as any)
const CardsRoute = CardsRouteImport.update({
  id: '/cards',
  path: '/cards',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculadoraRoute = CalculadoraRouteImport.update({
  id: '/calculadora',
  path: '/calculadora',
  getParentRoute: () => rootRouteImport,
} as any)
const BatimentosRoute = BatimentosRouteImport.update({
  id: '/batimentos',
  path: '/batimentos',
  getParentRoute: () => rootRouteImport,
} as any)
const BastidoresRoute = BastidoresRouteImport.update({
  id: '/bastidores',
  path: '/bastidores',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendamentoRoute = AgendamentoRouteImport.update({
  id: '/agendamento',
  path: '/agendamento',
  getParentRoute: () => rootRouteImport,
} as any)
const AcompanhanteRoute = AcompanhanteRouteImport.update({
  id: '/acompanhante',
  path: '/acompanhante',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VotarNomeTokenRoute = VotarNomeTokenRouteImport.update({
  id: '/votar-nome/$token',
  path: '/votar-nome/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const MedicosGoogleCallbackRoute = MedicosGoogleCallbackRouteImport.update({
  id: '/medicos_/google-callback',
  path: '/medicos/google-callback',
  getParentRoute: () => rootRouteImport,
} as any)
const MedicosCadastroRoute = MedicosCadastroRouteImport.update({
  id: '/medicos_/cadastro',
  path: '/medicos/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWhatsappRoute = ApiWhatsappRouteImport.update({
  id: '/api/whatsapp',
  path: '/api/whatsapp',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWaitlistTickRoute = ApiWaitlistTickRouteImport.update({
  id: '/api/waitlist-tick',
  path: '/api/waitlist-tick',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTranscribeRoute = ApiTranscribeRouteImport.update({
  id: '/api/transcribe',
  path: '/api/transcribe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStripeWebhookRoute = ApiStripeWebhookRouteImport.update({
  id: '/api/stripe-webhook',
  path: '/api/stripe-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPushWeeklyTickRoute = ApiPushWeeklyTickRouteImport.update({
  id: '/api/push-weekly-tick',
  path: '/api/push-weekly-tick',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNutritionRoute = ApiNutritionRouteImport.update({
  id: '/api/nutrition',
  path: '/api/nutrition',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMpWebhookRoute = ApiMpWebhookRouteImport.update({
  id: '/api/mp-webhook',
  path: '/api/mp-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInstagramWebhookRoute = ApiInstagramWebhookRouteImport.update({
  id: '/api/instagram-webhook',
  path: '/api/instagram-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCartaSemanalRoute = ApiCartaSemanalRouteImport.update({
  id: '/api/carta-semanal',
  path: '/api/carta-semanal',
  getParentRoute: () => rootRouteImport,
} as any)
const AlbumTokenRoute = AlbumTokenRouteImport.update({
  id: '/album/$token',
  path: '/album/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AcompanharTokenRoute = AcompanharTokenRouteImport.update({
  id: '/acompanhar/$token',
  path: '/acompanhar/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPainelRoute = AuthenticatedPainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMinhaContaRoute = AuthenticatedMinhaContaRouteImport.update({
  id: '/minha-conta',
  path: '/minha-conta',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiDoctorthinkTrainRoute = ApiDoctorthinkTrainRouteImport.update({
  id: '/api/doctorthink/train',
  path: '/api/doctorthink/train',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDoctorthinkAskRoute = ApiDoctorthinkAskRouteImport.update({
  id: '/api/doctorthink/ask',
  path: '/api/doctorthink/ask',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/acompanhante': typeof AcompanhanteRoute
  '/agendamento': typeof AgendamentoRoute
  '/auth': typeof AuthRoute
  '/bastidores': typeof BastidoresRoute
  '/batimentos': typeof BatimentosRoute
  '/calculadora': typeof CalculadoraRoute
  '/cards': typeof CardsRoute
  '/depoimentos': typeof DepoimentosRoute
  '/diabetes-gestacional': typeof DiabetesGestacionalRoute
  '/dpp': typeof DppRoute
  '/empresas': typeof EmpresasRoute
  '/encontrar-medico': typeof EncontrarMedicoRoute
  '/epds': typeof EpdsRoute
  '/experiencia': typeof ExperienciaRoute
  '/gestacao': typeof GestacaoRoute
  '/hospitais': typeof HospitaisRoute
  '/lives': typeof LivesRoute
  '/medicos': typeof MedicosRoute
  '/mitos': typeof MitosRoute
  '/modo-acompanhante': typeof ModoAcompanhanteRoute
  '/mural': typeof MuralRoute
  '/preview-chat': typeof PreviewChatRoute
  '/preview-conta': typeof PreviewContaRoute
  '/preview-grades': typeof PreviewGradesRoute
  '/preview-home': typeof PreviewHomeRoute
  '/preview-jogo': typeof PreviewJogoRoute
  '/preview-notificacoes': typeof PreviewNotificacoesRoute
  '/preview-saude': typeof PreviewSaudeRoute
  '/primeira-consulta': typeof PrimeiraConsultaRoute
  '/privacidade': typeof PrivacidadeRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
  '/tamanho-real': typeof TamanhoRealRoute
  '/termos': typeof TermosRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/minha-conta': typeof AuthenticatedMinhaContaRoute
  '/painel': typeof AuthenticatedPainelRoute
  '/acompanhar/$token': typeof AcompanharTokenRoute
  '/album/$token': typeof AlbumTokenRoute
  '/api/carta-semanal': typeof ApiCartaSemanalRoute
  '/api/chat': typeof ApiChatRoute
  '/api/instagram-webhook': typeof ApiInstagramWebhookRoute
  '/api/mp-webhook': typeof ApiMpWebhookRoute
  '/api/nutrition': typeof ApiNutritionRoute
  '/api/push-weekly-tick': typeof ApiPushWeeklyTickRoute
  '/api/stripe-webhook': typeof ApiStripeWebhookRoute
  '/api/transcribe': typeof ApiTranscribeRoute
  '/api/waitlist-tick': typeof ApiWaitlistTickRoute
  '/api/whatsapp': typeof ApiWhatsappRoute
  '/medicos/cadastro': typeof MedicosCadastroRoute
  '/medicos/google-callback': typeof MedicosGoogleCallbackRoute
  '/votar-nome/$token': typeof VotarNomeTokenRoute
  '/api/doctorthink/ask': typeof ApiDoctorthinkAskRoute
  '/api/doctorthink/train': typeof ApiDoctorthinkTrainRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/acompanhante': typeof AcompanhanteRoute
  '/agendamento': typeof AgendamentoRoute
  '/auth': typeof AuthRoute
  '/bastidores': typeof BastidoresRoute
  '/batimentos': typeof BatimentosRoute
  '/calculadora': typeof CalculadoraRoute
  '/cards': typeof CardsRoute
  '/depoimentos': typeof DepoimentosRoute
  '/diabetes-gestacional': typeof DiabetesGestacionalRoute
  '/dpp': typeof DppRoute
  '/empresas': typeof EmpresasRoute
  '/encontrar-medico': typeof EncontrarMedicoRoute
  '/epds': typeof EpdsRoute
  '/experiencia': typeof ExperienciaRoute
  '/gestacao': typeof GestacaoRoute
  '/hospitais': typeof HospitaisRoute
  '/lives': typeof LivesRoute
  '/medicos': typeof MedicosRoute
  '/mitos': typeof MitosRoute
  '/modo-acompanhante': typeof ModoAcompanhanteRoute
  '/mural': typeof MuralRoute
  '/preview-chat': typeof PreviewChatRoute
  '/preview-conta': typeof PreviewContaRoute
  '/preview-grades': typeof PreviewGradesRoute
  '/preview-home': typeof PreviewHomeRoute
  '/preview-jogo': typeof PreviewJogoRoute
  '/preview-notificacoes': typeof PreviewNotificacoesRoute
  '/preview-saude': typeof PreviewSaudeRoute
  '/primeira-consulta': typeof PrimeiraConsultaRoute
  '/privacidade': typeof PrivacidadeRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
  '/tamanho-real': typeof TamanhoRealRoute
  '/termos': typeof TermosRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/minha-conta': typeof AuthenticatedMinhaContaRoute
  '/painel': typeof AuthenticatedPainelRoute
  '/acompanhar/$token': typeof AcompanharTokenRoute
  '/album/$token': typeof AlbumTokenRoute
  '/api/carta-semanal': typeof ApiCartaSemanalRoute
  '/api/chat': typeof ApiChatRoute
  '/api/instagram-webhook': typeof ApiInstagramWebhookRoute
  '/api/mp-webhook': typeof ApiMpWebhookRoute
  '/api/nutrition': typeof ApiNutritionRoute
  '/api/push-weekly-tick': typeof ApiPushWeeklyTickRoute
  '/api/stripe-webhook': typeof ApiStripeWebhookRoute
  '/api/transcribe': typeof ApiTranscribeRoute
  '/api/waitlist-tick': typeof ApiWaitlistTickRoute
  '/api/whatsapp': typeof ApiWhatsappRoute
  '/medicos/cadastro': typeof MedicosCadastroRoute
  '/medicos/google-callback': typeof MedicosGoogleCallbackRoute
  '/votar-nome/$token': typeof VotarNomeTokenRoute
  '/api/doctorthink/ask': typeof ApiDoctorthinkAskRoute
  '/api/doctorthink/train': typeof ApiDoctorthinkTrainRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/acompanhante': typeof AcompanhanteRoute
  '/agendamento': typeof AgendamentoRoute
  '/auth': typeof AuthRoute
  '/bastidores': typeof BastidoresRoute
  '/batimentos': typeof BatimentosRoute
  '/calculadora': typeof CalculadoraRoute
  '/cards': typeof CardsRoute
  '/depoimentos': typeof DepoimentosRoute
  '/diabetes-gestacional': typeof DiabetesGestacionalRoute
  '/dpp': typeof DppRoute
  '/empresas': typeof EmpresasRoute
  '/encontrar-medico': typeof EncontrarMedicoRoute
  '/epds': typeof EpdsRoute
  '/experiencia': typeof ExperienciaRoute
  '/gestacao': typeof GestacaoRoute
  '/hospitais': typeof HospitaisRoute
  '/lives': typeof LivesRoute
  '/medicos': typeof MedicosRoute
  '/mitos': typeof MitosRoute
  '/modo-acompanhante': typeof ModoAcompanhanteRoute
  '/mural': typeof MuralRoute
  '/preview-chat': typeof PreviewChatRoute
  '/preview-conta': typeof PreviewContaRoute
  '/preview-grades': typeof PreviewGradesRoute
  '/preview-home': typeof PreviewHomeRoute
  '/preview-jogo': typeof PreviewJogoRoute
  '/preview-notificacoes': typeof PreviewNotificacoesRoute
  '/preview-saude': typeof PreviewSaudeRoute
  '/primeira-consulta': typeof PrimeiraConsultaRoute
  '/privacidade': typeof PrivacidadeRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
  '/tamanho-real': typeof TamanhoRealRoute
  '/termos': typeof TermosRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/minha-conta': typeof AuthenticatedMinhaContaRoute
  '/_authenticated/painel': typeof AuthenticatedPainelRoute
  '/acompanhar/$token': typeof AcompanharTokenRoute
  '/album/$token': typeof AlbumTokenRoute
  '/api/carta-semanal': typeof ApiCartaSemanalRoute
  '/api/chat': typeof ApiChatRoute
  '/api/instagram-webhook': typeof ApiInstagramWebhookRoute
  '/api/mp-webhook': typeof ApiMpWebhookRoute
  '/api/nutrition': typeof ApiNutritionRoute
  '/api/push-weekly-tick': typeof ApiPushWeeklyTickRoute
  '/api/stripe-webhook': typeof ApiStripeWebhookRoute
  '/api/transcribe': typeof ApiTranscribeRoute
  '/api/waitlist-tick': typeof ApiWaitlistTickRoute
  '/api/whatsapp': typeof ApiWhatsappRoute
  '/medicos_/cadastro': typeof MedicosCadastroRoute
  '/medicos_/google-callback': typeof MedicosGoogleCallbackRoute
  '/votar-nome/$token': typeof VotarNomeTokenRoute
  '/api/doctorthink/ask': typeof ApiDoctorthinkAskRoute
  '/api/doctorthink/train': typeof ApiDoctorthinkTrainRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/acompanhante'
    | '/agendamento'
    | '/auth'
    | '/bastidores'
    | '/batimentos'
    | '/calculadora'
    | '/cards'
    | '/depoimentos'
    | '/diabetes-gestacional'
    | '/dpp'
    | '/empresas'
    | '/encontrar-medico'
    | '/epds'
    | '/experiencia'
    | '/gestacao'
    | '/hospitais'
    | '/lives'
    | '/medicos'
    | '/mitos'
    | '/modo-acompanhante'
    | '/mural'
    | '/preview-chat'
    | '/preview-conta'
    | '/preview-grades'
    | '/preview-home'
    | '/preview-jogo'
    | '/preview-notificacoes'
    | '/preview-saude'
    | '/primeira-consulta'
    | '/privacidade'
    | '/sitemap.xml'
    | '/sobre'
    | '/tamanho-real'
    | '/termos'
    | '/admin'
    | '/minha-conta'
    | '/painel'
    | '/acompanhar/$token'
    | '/album/$token'
    | '/api/carta-semanal'
    | '/api/chat'
    | '/api/instagram-webhook'
    | '/api/mp-webhook'
    | '/api/nutrition'
    | '/api/push-weekly-tick'
    | '/api/stripe-webhook'
    | '/api/transcribe'
    | '/api/waitlist-tick'
    | '/api/whatsapp'
    | '/medicos/cadastro'
    | '/medicos/google-callback'
    | '/votar-nome/$token'
    | '/api/doctorthink/ask'
    | '/api/doctorthink/train'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/acompanhante'
    | '/agendamento'
    | '/auth'
    | '/bastidores'
    | '/batimentos'
    | '/calculadora'
    | '/cards'
    | '/depoimentos'
    | '/diabetes-gestacional'
    | '/dpp'
    | '/empresas'
    | '/encontrar-medico'
    | '/epds'
    | '/experiencia'
    | '/gestacao'
    | '/hospitais'
    | '/lives'
    | '/medicos'
    | '/mitos'
    | '/modo-acompanhante'
    | '/mural'
    | '/preview-chat'
    | '/preview-conta'
    | '/preview-grades'
    | '/preview-home'
    | '/preview-jogo'
    | '/preview-notificacoes'
    | '/preview-saude'
    | '/primeira-consulta'
    | '/privacidade'
    | '/sitemap.xml'
    | '/sobre'
    | '/tamanho-real'
    | '/termos'
    | '/admin'
    | '/minha-conta'
    | '/painel'
    | '/acompanhar/$token'
    | '/album/$token'
    | '/api/carta-semanal'
    | '/api/chat'
    | '/api/instagram-webhook'
    | '/api/mp-webhook'
    | '/api/nutrition'
    | '/api/push-weekly-tick'
    | '/api/stripe-webhook'
    | '/api/transcribe'
    | '/api/waitlist-tick'
    | '/api/whatsapp'
    | '/medicos/cadastro'
    | '/medicos/google-callback'
    | '/votar-nome/$token'
    | '/api/doctorthink/ask'
    | '/api/doctorthink/train'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/acompanhante'
    | '/agendamento'
    | '/auth'
    | '/bastidores'
    | '/batimentos'
    | '/calculadora'
    | '/cards'
    | '/depoimentos'
    | '/diabetes-gestacional'
    | '/dpp'
    | '/empresas'
    | '/encontrar-medico'
    | '/epds'
    | '/experiencia'
    | '/gestacao'
    | '/hospitais'
    | '/lives'
    | '/medicos'
    | '/mitos'
    | '/modo-acompanhante'
    | '/mural'
    | '/preview-chat'
    | '/preview-conta'
    | '/preview-grades'
    | '/preview-home'
    | '/preview-jogo'
    | '/preview-notificacoes'
    | '/preview-saude'
    | '/primeira-consulta'
    | '/privacidade'
    | '/sitemap.xml'
    | '/sobre'
    | '/tamanho-real'
    | '/termos'
    | '/_authenticated/admin'
    | '/_authenticated/minha-conta'
    | '/_authenticated/painel'
    | '/acompanhar/$token'
    | '/album/$token'
    | '/api/carta-semanal'
    | '/api/chat'
    | '/api/instagram-webhook'
    | '/api/mp-webhook'
    | '/api/nutrition'
    | '/api/push-weekly-tick'
    | '/api/stripe-webhook'
    | '/api/transcribe'
    | '/api/waitlist-tick'
    | '/api/whatsapp'
    | '/medicos_/cadastro'
    | '/medicos_/google-callback'
    | '/votar-nome/$token'
    | '/api/doctorthink/ask'
    | '/api/doctorthink/train'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AcompanhanteRoute: typeof AcompanhanteRoute
  AgendamentoRoute: typeof AgendamentoRoute
  AuthRoute: typeof AuthRoute
  BastidoresRoute: typeof BastidoresRoute
  BatimentosRoute: typeof BatimentosRoute
  CalculadoraRoute: typeof CalculadoraRoute
  CardsRoute: typeof CardsRoute
  DepoimentosRoute: typeof DepoimentosRoute
  DiabetesGestacionalRoute: typeof DiabetesGestacionalRoute
  DppRoute: typeof DppRoute
  EmpresasRoute: typeof EmpresasRoute
  EncontrarMedicoRoute: typeof EncontrarMedicoRoute
  EpdsRoute: typeof EpdsRoute
  ExperienciaRoute: typeof ExperienciaRoute
  GestacaoRoute: typeof GestacaoRoute
  HospitaisRoute: typeof HospitaisRoute
  LivesRoute: typeof LivesRoute
  MedicosRoute: typeof MedicosRoute
  MitosRoute: typeof MitosRoute
  ModoAcompanhanteRoute: typeof ModoAcompanhanteRoute
  MuralRoute: typeof MuralRoute
  PreviewChatRoute: typeof PreviewChatRoute
  PreviewContaRoute: typeof PreviewContaRoute
  PreviewGradesRoute: typeof PreviewGradesRoute
  PreviewHomeRoute: typeof PreviewHomeRoute
  PreviewJogoRoute: typeof PreviewJogoRoute
  PreviewNotificacoesRoute: typeof PreviewNotificacoesRoute
  PreviewSaudeRoute: typeof PreviewSaudeRoute
  PrimeiraConsultaRoute: typeof PrimeiraConsultaRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SobreRoute: typeof SobreRoute
  TamanhoRealRoute: typeof TamanhoRealRoute
  TermosRoute: typeof TermosRoute
  AcompanharTokenRoute: typeof AcompanharTokenRoute
  AlbumTokenRoute: typeof AlbumTokenRoute
  ApiCartaSemanalRoute: typeof ApiCartaSemanalRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiInstagramWebhookRoute: typeof ApiInstagramWebhookRoute
  ApiMpWebhookRoute: typeof ApiMpWebhookRoute
  ApiNutritionRoute: typeof ApiNutritionRoute
  ApiPushWeeklyTickRoute: typeof ApiPushWeeklyTickRoute
  ApiStripeWebhookRoute: typeof ApiStripeWebhookRoute
  ApiTranscribeRoute: typeof ApiTranscribeRoute
  ApiWaitlistTickRoute: typeof ApiWaitlistTickRoute
  ApiWhatsappRoute: typeof ApiWhatsappRoute
  MedicosCadastroRoute: typeof MedicosCadastroRoute
  MedicosGoogleCallbackRoute: typeof MedicosGoogleCallbackRoute
  VotarNomeTokenRoute: typeof VotarNomeTokenRoute
  ApiDoctorthinkAskRoute: typeof ApiDoctorthinkAskRoute
  ApiDoctorthinkTrainRoute: typeof ApiDoctorthinkTrainRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tamanho-real': {
      id: '/tamanho-real'
      path: '/tamanho-real'
      fullPath: '/tamanho-real'
      preLoaderRoute: typeof TamanhoRealRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/primeira-consulta': {
      id: '/primeira-consulta'
      path: '/primeira-consulta'
      fullPath: '/primeira-consulta'
      preLoaderRoute: typeof PrimeiraConsultaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preview-saude': {
      id: '/preview-saude'
      path: '/preview-saude'
      fullPath: '/preview-saude'
      preLoaderRoute: typeof PreviewSaudeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preview-notificacoes': {
      id: '/preview-notificacoes'
      path: '/preview-notificacoes'
      fullPath: '/preview-notificacoes'
      preLoaderRoute: typeof PreviewNotificacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preview-jogo': {
      id: '/preview-jogo'
      path: '/preview-jogo'
      fullPath: '/preview-jogo'
      preLoaderRoute: typeof PreviewJogoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preview-home': {
      id: '/preview-home'
      path: '/preview-home'
      fullPath: '/preview-home'
      preLoaderRoute: typeof PreviewHomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preview-grades': {
      id: '/preview-grades'
      path: '/preview-grades'
      fullPath: '/preview-grades'
      preLoaderRoute: typeof PreviewGradesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preview-conta': {
      id: '/preview-conta'
      path: '/preview-conta'
      fullPath: '/preview-conta'
      preLoaderRoute: typeof PreviewContaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preview-chat': {
      id: '/preview-chat'
      path: '/preview-chat'
      fullPath: '/preview-chat'
      preLoaderRoute: typeof PreviewChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mural': {
      id: '/mural'
      path: '/mural'
      fullPath: '/mural'
      preLoaderRoute: typeof MuralRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modo-acompanhante': {
      id: '/modo-acompanhante'
      path: '/modo-acompanhante'
      fullPath: '/modo-acompanhante'
      preLoaderRoute: typeof ModoAcompanhanteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mitos': {
      id: '/mitos'
      path: '/mitos'
      fullPath: '/mitos'
      preLoaderRoute: typeof MitosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/medicos': {
      id: '/medicos'
      path: '/medicos'
      fullPath: '/medicos'
      preLoaderRoute: typeof MedicosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lives': {
      id: '/lives'
      path: '/lives'
      fullPath: '/lives'
      preLoaderRoute: typeof LivesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hospitais': {
      id: '/hospitais'
      path: '/hospitais'
      fullPath: '/hospitais'
      preLoaderRoute: typeof HospitaisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gestacao': {
      id: '/gestacao'
      path: '/gestacao'
      fullPath: '/gestacao'
      preLoaderRoute: typeof GestacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experiencia': {
      id: '/experiencia'
      path: '/experiencia'
      fullPath: '/experiencia'
      preLoaderRoute: typeof ExperienciaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/epds': {
      id: '/epds'
      path: '/epds'
      fullPath: '/epds'
      preLoaderRoute: typeof EpdsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/encontrar-medico': {
      id: '/encontrar-medico'
      path: '/encontrar-medico'
      fullPath: '/encontrar-medico'
      preLoaderRoute: typeof EncontrarMedicoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/empresas': {
      id: '/empresas'
      path: '/empresas'
      fullPath: '/empresas'
      preLoaderRoute: typeof EmpresasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dpp': {
      id: '/dpp'
      path: '/dpp'
      fullPath: '/dpp'
      preLoaderRoute: typeof DppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diabetes-gestacional': {
      id: '/diabetes-gestacional'
      path: '/diabetes-gestacional'
      fullPath: '/diabetes-gestacional'
      preLoaderRoute: typeof DiabetesGestacionalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/depoimentos': {
      id: '/depoimentos'
      path: '/depoimentos'
      fullPath: '/depoimentos'
      preLoaderRoute: typeof DepoimentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cards': {
      id: '/cards'
      path: '/cards'
      fullPath: '/cards'
      preLoaderRoute: typeof CardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculadora': {
      id: '/calculadora'
      path: '/calculadora'
      fullPath: '/calculadora'
      preLoaderRoute: typeof CalculadoraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/batimentos': {
      id: '/batimentos'
      path: '/batimentos'
      fullPath: '/batimentos'
      preLoaderRoute: typeof BatimentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bastidores': {
      id: '/bastidores'
      path: '/bastidores'
      fullPath: '/bastidores'
      preLoaderRoute: typeof BastidoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agendamento': {
      id: '/agendamento'
      path: '/agendamento'
      fullPath: '/agendamento'
      preLoaderRoute: typeof AgendamentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acompanhante': {
      id: '/acompanhante'
      path: '/acompanhante'
      fullPath: '/acompanhante'
      preLoaderRoute: typeof AcompanhanteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/votar-nome/$token': {
      id: '/votar-nome/$token'
      path: '/votar-nome/$token'
      fullPath: '/votar-nome/$token'
      preLoaderRoute: typeof VotarNomeTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/medicos_/google-callback': {
      id: '/medicos_/google-callback'
      path: '/medicos/google-callback'
      fullPath: '/medicos/google-callback'
      preLoaderRoute: typeof MedicosGoogleCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/medicos_/cadastro': {
      id: '/medicos_/cadastro'
      path: '/medicos/cadastro'
      fullPath: '/medicos/cadastro'
      preLoaderRoute: typeof MedicosCadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/whatsapp': {
      id: '/api/whatsapp'
      path: '/api/whatsapp'
      fullPath: '/api/whatsapp'
      preLoaderRoute: typeof ApiWhatsappRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/waitlist-tick': {
      id: '/api/waitlist-tick'
      path: '/api/waitlist-tick'
      fullPath: '/api/waitlist-tick'
      preLoaderRoute: typeof ApiWaitlistTickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/transcribe': {
      id: '/api/transcribe'
      path: '/api/transcribe'
      fullPath: '/api/transcribe'
      preLoaderRoute: typeof ApiTranscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stripe-webhook': {
      id: '/api/stripe-webhook'
      path: '/api/stripe-webhook'
      fullPath: '/api/stripe-webhook'
      preLoaderRoute: typeof ApiStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/push-weekly-tick': {
      id: '/api/push-weekly-tick'
      path: '/api/push-weekly-tick'
      fullPath: '/api/push-weekly-tick'
      preLoaderRoute: typeof ApiPushWeeklyTickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/nutrition': {
      id: '/api/nutrition'
      path: '/api/nutrition'
      fullPath: '/api/nutrition'
      preLoaderRoute: typeof ApiNutritionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mp-webhook': {
      id: '/api/mp-webhook'
      path: '/api/mp-webhook'
      fullPath: '/api/mp-webhook'
      preLoaderRoute: typeof ApiMpWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/instagram-webhook': {
      id: '/api/instagram-webhook'
      path: '/api/instagram-webhook'
      fullPath: '/api/instagram-webhook'
      preLoaderRoute: typeof ApiInstagramWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/carta-semanal': {
      id: '/api/carta-semanal'
      path: '/api/carta-semanal'
      fullPath: '/api/carta-semanal'
      preLoaderRoute: typeof ApiCartaSemanalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/album/$token': {
      id: '/album/$token'
      path: '/album/$token'
      fullPath: '/album/$token'
      preLoaderRoute: typeof AlbumTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acompanhar/$token': {
      id: '/acompanhar/$token'
      path: '/acompanhar/$token'
      fullPath: '/acompanhar/$token'
      preLoaderRoute: typeof AcompanharTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/painel': {
      id: '/_authenticated/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof AuthenticatedPainelRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/minha-conta': {
      id: '/_authenticated/minha-conta'
      path: '/minha-conta'
      fullPath: '/minha-conta'
      preLoaderRoute: typeof AuthenticatedMinhaContaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/doctorthink/train': {
      id: '/api/doctorthink/train'
      path: '/api/doctorthink/train'
      fullPath: '/api/doctorthink/train'
      preLoaderRoute: typeof ApiDoctorthinkTrainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/doctorthink/ask': {
      id: '/api/doctorthink/ask'
      path: '/api/doctorthink/ask'
      fullPath: '/api/doctorthink/ask'
      preLoaderRoute: typeof ApiDoctorthinkAskRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedMinhaContaRoute: typeof AuthenticatedMinhaContaRoute
  AuthenticatedPainelRoute: typeof AuthenticatedPainelRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedMinhaContaRoute: AuthenticatedMinhaContaRoute,
  AuthenticatedPainelRoute: AuthenticatedPainelRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AcompanhanteRoute: AcompanhanteRoute,
  AgendamentoRoute: AgendamentoRoute,
  AuthRoute: AuthRoute,
  BastidoresRoute: BastidoresRoute,
  BatimentosRoute: BatimentosRoute,
  CalculadoraRoute: CalculadoraRoute,
  CardsRoute: CardsRoute,
  DepoimentosRoute: DepoimentosRoute,
  DiabetesGestacionalRoute: DiabetesGestacionalRoute,
  DppRoute: DppRoute,
  EmpresasRoute: EmpresasRoute,
  EncontrarMedicoRoute: EncontrarMedicoRoute,
  EpdsRoute: EpdsRoute,
  ExperienciaRoute: ExperienciaRoute,
  GestacaoRoute: GestacaoRoute,
  HospitaisRoute: HospitaisRoute,
  LivesRoute: LivesRoute,
  MedicosRoute: MedicosRoute,
  MitosRoute: MitosRoute,
  ModoAcompanhanteRoute: ModoAcompanhanteRoute,
  MuralRoute: MuralRoute,
  PreviewChatRoute: PreviewChatRoute,
  PreviewContaRoute: PreviewContaRoute,
  PreviewGradesRoute: PreviewGradesRoute,
  PreviewHomeRoute: PreviewHomeRoute,
  PreviewJogoRoute: PreviewJogoRoute,
  PreviewNotificacoesRoute: PreviewNotificacoesRoute,
  PreviewSaudeRoute: PreviewSaudeRoute,
  PrimeiraConsultaRoute: PrimeiraConsultaRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SobreRoute: SobreRoute,
  TamanhoRealRoute: TamanhoRealRoute,
  TermosRoute: TermosRoute,
  AcompanharTokenRoute: AcompanharTokenRoute,
  AlbumTokenRoute: AlbumTokenRoute,
  ApiCartaSemanalRoute: ApiCartaSemanalRoute,
  ApiChatRoute: ApiChatRoute,
  ApiInstagramWebhookRoute: ApiInstagramWebhookRoute,
  ApiMpWebhookRoute: ApiMpWebhookRoute,
  ApiNutritionRoute: ApiNutritionRoute,
  ApiPushWeeklyTickRoute: ApiPushWeeklyTickRoute,
  ApiStripeWebhookRoute: ApiStripeWebhookRoute,
  ApiTranscribeRoute: ApiTranscribeRoute,
  ApiWaitlistTickRoute: ApiWaitlistTickRoute,
  ApiWhatsappRoute: ApiWhatsappRoute,
  MedicosCadastroRoute: MedicosCadastroRoute,
  MedicosGoogleCallbackRoute: MedicosGoogleCallbackRoute,
  VotarNomeTokenRoute: VotarNomeTokenRoute,
  ApiDoctorthinkAskRoute: ApiDoctorthinkAskRoute,
  ApiDoctorthinkTrainRoute: ApiDoctorthinkTrainRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
