/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TamanhoRealRouteImport } from './routes/tamanho-real'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as PrimeiraConsultaRouteImport } from './routes/primeira-consulta'
import { Route as MuralRouteImport } from './routes/mural'
import { Route as ModoAcompanhanteRouteImport } from './routes/modo-acompanhante'
import { Route as MitosRouteImport } from './routes/mitos'
import { Route as MedicosRouteImport } from './routes/medicos'
import { Route as LivesRouteImport } from './routes/lives'
import { Route as HospitaisRouteImport } from './routes/hospitais'
import { Route as GestacaoRouteImport } from './routes/gestacao'
import { Route as EpdsRouteImport } from './routes/epds'
import { Route as EmpresasRouteImport } from './routes/empresas'
import { Route as DppRouteImport } from './routes/dpp'
import { Route as DiabetesGestacionalRouteImport } from './routes/diabetes-gestacional'
import { Route as DepoimentosRouteImport } from './routes/depoimentos'
import { Route as CardsRouteImport } from './routes/cards'
import { Route as CalculadoraRouteImport } from './routes/calculadora'
import { Route as BatimentosRouteImport } from './routes/batimentos'
import { Route as BastidoresRouteImport } from './routes/bastidores'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AgendamentoRouteImport } from './routes/agendamento'
import { Route as AcompanhanteRouteImport } from './routes/acompanhante'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VotarNomeTokenRouteImport } from './routes/votar-nome.$token'
import { Route as MedicosCadastroRouteImport } from './routes/medicos_.cadastro'
import { Route as ApiWhatsappRouteImport } from './routes/api/whatsapp'
import { Route as ApiTranscribeRouteImport } from './routes/api/transcribe'
import { Route as ApiNutritionRouteImport } from './routes/api/nutrition'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ApiCartaSemanalRouteImport } from './routes/api/carta-semanal'
import { Route as AlbumTokenRouteImport } from './routes/album.$token'
import { Route as AcompanharTokenRouteImport } from './routes/acompanhar.$token'
import { Route as AuthenticatedPainelRouteImport } from './routes/_authenticated/painel'
import { Route as AuthenticatedMinhaContaRouteImport } from './routes/_authenticated/minha-conta'

const TamanhoRealRoute = TamanhoRealRouteImport.update({
  id: '/tamanho-real',
  path: '/tamanho-real',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const PrimeiraConsultaRoute = PrimeiraConsultaRouteImport.update({
  id: '/primeira-consulta',
  path: '/primeira-consulta',
  getParentRoute: () => rootRouteImport,
} as any)
const MuralRoute = MuralRouteImport.update({
  id: '/mural',
  path: '/mural',
  getParentRoute: () => rootRouteImport,
} as any)
const ModoAcompanhanteRoute = ModoAcompanhanteRouteImport.update({
  id: '/modo-acompanhante',
  path: '/modo-acompanhante',
  getParentRoute: () => rootRouteImport,
} as any)
const MitosRoute = MitosRouteImport.update({
  id: '/mitos',
  path: '/mitos',
  getParentRoute: () => rootRouteImport,
} as any)
const MedicosRoute = MedicosRouteImport.update({
  id: '/medicos',
  path: '/medicos',
  getParentRoute: () => rootRouteImport,
} as any)
const LivesRoute = LivesRouteImport.update({
  id: '/lives',
  path: '/lives',
  getParentRoute: () => rootRouteImport,
} as any)
const HospitaisRoute = HospitaisRouteImport.update({
  id: '/hospitais',
  path: '/hospitais',
  getParentRoute: () => rootRouteImport,
} as any)
const GestacaoRoute = GestacaoRouteImport.update({
  id: '/gestacao',
  path: '/gestacao',
  getParentRoute: () => rootRouteImport,
} as any)
const EpdsRoute = EpdsRouteImport.update({
  id: '/epds',
  path: '/epds',
  getParentRoute: () => rootRouteImport,
} as any)
const EmpresasRoute = EmpresasRouteImport.update({
  id: '/empresas',
  path: '/empresas',
  getParentRoute: () => rootRouteImport,
} as any)
const DppRoute = DppRouteImport.update({
  id: '/dpp',
  path: '/dpp',
  getParentRoute: () => rootRouteImport,
} as any)
const DiabetesGestacionalRoute = DiabetesGestacionalRouteImport.update({
  id: '/diabetes-gestacional',
  path: '/diabetes-gestacional',
  getParentRoute: () => rootRouteImport,
} as any)
const DepoimentosRoute = DepoimentosRouteImport.update({
  id: '/depoimentos',
  path: '/depoimentos',
  getParentRoute: () => rootRouteImport,
} as any)
const CardsRoute = CardsRouteImport.update({
  id: '/cards',
  path: '/cards',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculadoraRoute = CalculadoraRouteImport.update({
  id: '/calculadora',
  path: '/calculadora',
  getParentRoute: () => rootRouteImport,
} as any)
const BatimentosRoute = BatimentosRouteImport.update({
  id: '/batimentos',
  path: '/batimentos',
  getParentRoute: () => rootRouteImport,
} as any)
const BastidoresRoute = BastidoresRouteImport.update({
  id: '/bastidores',
  path: '/bastidores',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendamentoRoute = AgendamentoRouteImport.update({
  id: '/agendamento',
  path: '/agendamento',
  getParentRoute: () => rootRouteImport,
} as any)
const AcompanhanteRoute = AcompanhanteRouteImport.update({
  id: '/acompanhante',
  path: '/acompanhante',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VotarNomeTokenRoute = VotarNomeTokenRouteImport.update({
  id: '/votar-nome/$token',
  path: '/votar-nome/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const MedicosCadastroRoute = MedicosCadastroRouteImport.update({
  id: '/medicos_/cadastro',
  path: '/medicos/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWhatsappRoute = ApiWhatsappRouteImport.update({
  id: '/api/whatsapp',
  path: '/api/whatsapp',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTranscribeRoute = ApiTranscribeRouteImport.update({
  id: '/api/transcribe',
  path: '/api/transcribe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNutritionRoute = ApiNutritionRouteImport.update({
  id: '/api/nutrition',
  path: '/api/nutrition',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCartaSemanalRoute = ApiCartaSemanalRouteImport.update({
  id: '/api/carta-semanal',
  path: '/api/carta-semanal',
  getParentRoute: () => rootRouteImport,
} as any)
const AlbumTokenRoute = AlbumTokenRouteImport.update({
  id: '/album/$token',
  path: '/album/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AcompanharTokenRoute = AcompanharTokenRouteImport.update({
  id: '/acompanhar/$token',
  path: '/acompanhar/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPainelRoute = AuthenticatedPainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMinhaContaRoute = AuthenticatedMinhaContaRouteImport.update({
  id: '/minha-conta',
  path: '/minha-conta',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/acompanhante': typeof AcompanhanteRoute
  '/agendamento': typeof AgendamentoRoute
  '/auth': typeof AuthRoute
  '/bastidores': typeof BastidoresRoute
  '/batimentos': typeof BatimentosRoute
  '/calculadora': typeof CalculadoraRoute
  '/cards': typeof CardsRoute
  '/depoimentos': typeof DepoimentosRoute
  '/diabetes-gestacional': typeof DiabetesGestacionalRoute
  '/dpp': typeof DppRoute
  '/empresas': typeof EmpresasRoute
  '/epds': typeof EpdsRoute
  '/gestacao': typeof GestacaoRoute
  '/hospitais': typeof HospitaisRoute
  '/lives': typeof LivesRoute
  '/medicos': typeof MedicosRoute
  '/mitos': typeof MitosRoute
  '/modo-acompanhante': typeof ModoAcompanhanteRoute
  '/mural': typeof MuralRoute
  '/primeira-consulta': typeof PrimeiraConsultaRoute
  '/privacidade': typeof PrivacidadeRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
  '/tamanho-real': typeof TamanhoRealRoute
  '/minha-conta': typeof AuthenticatedMinhaContaRoute
  '/painel': typeof AuthenticatedPainelRoute
  '/acompanhar/$token': typeof AcompanharTokenRoute
  '/album/$token': typeof AlbumTokenRoute
  '/api/carta-semanal': typeof ApiCartaSemanalRoute
  '/api/chat': typeof ApiChatRoute
  '/api/nutrition': typeof ApiNutritionRoute
  '/api/transcribe': typeof ApiTranscribeRoute
  '/api/whatsapp': typeof ApiWhatsappRoute
  '/medicos/cadastro': typeof MedicosCadastroRoute
  '/votar-nome/$token': typeof VotarNomeTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/acompanhante': typeof AcompanhanteRoute
  '/agendamento': typeof AgendamentoRoute
  '/auth': typeof AuthRoute
  '/bastidores': typeof BastidoresRoute
  '/batimentos': typeof BatimentosRoute
  '/calculadora': typeof CalculadoraRoute
  '/cards': typeof CardsRoute
  '/depoimentos': typeof DepoimentosRoute
  '/diabetes-gestacional': typeof DiabetesGestacionalRoute
  '/dpp': typeof DppRoute
  '/empresas': typeof EmpresasRoute
  '/epds': typeof EpdsRoute
  '/gestacao': typeof GestacaoRoute
  '/hospitais': typeof HospitaisRoute
  '/lives': typeof LivesRoute
  '/medicos': typeof MedicosRoute
  '/mitos': typeof MitosRoute
  '/modo-acompanhante': typeof ModoAcompanhanteRoute
  '/mural': typeof MuralRoute
  '/primeira-consulta': typeof PrimeiraConsultaRoute
  '/privacidade': typeof PrivacidadeRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
  '/tamanho-real': typeof TamanhoRealRoute
  '/minha-conta': typeof AuthenticatedMinhaContaRoute
  '/painel': typeof AuthenticatedPainelRoute
  '/acompanhar/$token': typeof AcompanharTokenRoute
  '/album/$token': typeof AlbumTokenRoute
  '/api/carta-semanal': typeof ApiCartaSemanalRoute
  '/api/chat': typeof ApiChatRoute
  '/api/nutrition': typeof ApiNutritionRoute
  '/api/transcribe': typeof ApiTranscribeRoute
  '/api/whatsapp': typeof ApiWhatsappRoute
  '/medicos/cadastro': typeof MedicosCadastroRoute
  '/votar-nome/$token': typeof VotarNomeTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/acompanhante': typeof AcompanhanteRoute
  '/agendamento': typeof AgendamentoRoute
  '/auth': typeof AuthRoute
  '/bastidores': typeof BastidoresRoute
  '/batimentos': typeof BatimentosRoute
  '/calculadora': typeof CalculadoraRoute
  '/cards': typeof CardsRoute
  '/depoimentos': typeof DepoimentosRoute
  '/diabetes-gestacional': typeof DiabetesGestacionalRoute
  '/dpp': typeof DppRoute
  '/empresas': typeof EmpresasRoute
  '/epds': typeof EpdsRoute
  '/gestacao': typeof GestacaoRoute
  '/hospitais': typeof HospitaisRoute
  '/lives': typeof LivesRoute
  '/medicos': typeof MedicosRoute
  '/mitos': typeof MitosRoute
  '/modo-acompanhante': typeof ModoAcompanhanteRoute
  '/mural': typeof MuralRoute
  '/primeira-consulta': typeof PrimeiraConsultaRoute
  '/privacidade': typeof PrivacidadeRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
  '/tamanho-real': typeof TamanhoRealRoute
  '/_authenticated/minha-conta': typeof AuthenticatedMinhaContaRoute
  '/_authenticated/painel': typeof AuthenticatedPainelRoute
  '/acompanhar/$token': typeof AcompanharTokenRoute
  '/album/$token': typeof AlbumTokenRoute
  '/api/carta-semanal': typeof ApiCartaSemanalRoute
  '/api/chat': typeof ApiChatRoute
  '/api/nutrition': typeof ApiNutritionRoute
  '/api/transcribe': typeof ApiTranscribeRoute
  '/api/whatsapp': typeof ApiWhatsappRoute
  '/medicos_/cadastro': typeof MedicosCadastroRoute
  '/votar-nome/$token': typeof VotarNomeTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/acompanhante'
    | '/agendamento'
    | '/auth'
    | '/bastidores'
    | '/batimentos'
    | '/calculadora'
    | '/cards'
    | '/depoimentos'
    | '/diabetes-gestacional'
    | '/dpp'
    | '/empresas'
    | '/epds'
    | '/gestacao'
    | '/hospitais'
    | '/lives'
    | '/medicos'
    | '/mitos'
    | '/modo-acompanhante'
    | '/mural'
    | '/primeira-consulta'
    | '/privacidade'
    | '/sitemap.xml'
    | '/sobre'
    | '/tamanho-real'
    | '/minha-conta'
    | '/painel'
    | '/acompanhar/$token'
    | '/album/$token'
    | '/api/carta-semanal'
    | '/api/chat'
    | '/api/nutrition'
    | '/api/transcribe'
    | '/api/whatsapp'
    | '/medicos/cadastro'
    | '/votar-nome/$token'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/acompanhante'
    | '/agendamento'
    | '/auth'
    | '/bastidores'
    | '/batimentos'
    | '/calculadora'
    | '/cards'
    | '/depoimentos'
    | '/diabetes-gestacional'
    | '/dpp'
    | '/empresas'
    | '/epds'
    | '/gestacao'
    | '/hospitais'
    | '/lives'
    | '/medicos'
    | '/mitos'
    | '/modo-acompanhante'
    | '/mural'
    | '/primeira-consulta'
    | '/privacidade'
    | '/sitemap.xml'
    | '/sobre'
    | '/tamanho-real'
    | '/minha-conta'
    | '/painel'
    | '/acompanhar/$token'
    | '/album/$token'
    | '/api/carta-semanal'
    | '/api/chat'
    | '/api/nutrition'
    | '/api/transcribe'
    | '/api/whatsapp'
    | '/medicos/cadastro'
    | '/votar-nome/$token'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/acompanhante'
    | '/agendamento'
    | '/auth'
    | '/bastidores'
    | '/batimentos'
    | '/calculadora'
    | '/cards'
    | '/depoimentos'
    | '/diabetes-gestacional'
    | '/dpp'
    | '/empresas'
    | '/epds'
    | '/gestacao'
    | '/hospitais'
    | '/lives'
    | '/medicos'
    | '/mitos'
    | '/modo-acompanhante'
    | '/mural'
    | '/primeira-consulta'
    | '/privacidade'
    | '/sitemap.xml'
    | '/sobre'
    | '/tamanho-real'
    | '/_authenticated/minha-conta'
    | '/_authenticated/painel'
    | '/acompanhar/$token'
    | '/album/$token'
    | '/api/carta-semanal'
    | '/api/chat'
    | '/api/nutrition'
    | '/api/transcribe'
    | '/api/whatsapp'
    | '/medicos_/cadastro'
    | '/votar-nome/$token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AcompanhanteRoute: typeof AcompanhanteRoute
  AgendamentoRoute: typeof AgendamentoRoute
  AuthRoute: typeof AuthRoute
  BastidoresRoute: typeof BastidoresRoute
  BatimentosRoute: typeof BatimentosRoute
  CalculadoraRoute: typeof CalculadoraRoute
  CardsRoute: typeof CardsRoute
  DepoimentosRoute: typeof DepoimentosRoute
  DiabetesGestacionalRoute: typeof DiabetesGestacionalRoute
  DppRoute: typeof DppRoute
  EmpresasRoute: typeof EmpresasRoute
  EpdsRoute: typeof EpdsRoute
  GestacaoRoute: typeof GestacaoRoute
  HospitaisRoute: typeof HospitaisRoute
  LivesRoute: typeof LivesRoute
  MedicosRoute: typeof MedicosRoute
  MitosRoute: typeof MitosRoute
  ModoAcompanhanteRoute: typeof ModoAcompanhanteRoute
  MuralRoute: typeof MuralRoute
  PrimeiraConsultaRoute: typeof PrimeiraConsultaRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SobreRoute: typeof SobreRoute
  TamanhoRealRoute: typeof TamanhoRealRoute
  AcompanharTokenRoute: typeof AcompanharTokenRoute
  AlbumTokenRoute: typeof AlbumTokenRoute
  ApiCartaSemanalRoute: typeof ApiCartaSemanalRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiNutritionRoute: typeof ApiNutritionRoute
  ApiTranscribeRoute: typeof ApiTranscribeRoute
  ApiWhatsappRoute: typeof ApiWhatsappRoute
  MedicosCadastroRoute: typeof MedicosCadastroRoute
  VotarNomeTokenRoute: typeof VotarNomeTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tamanho-real': {
      id: '/tamanho-real'
      path: '/tamanho-real'
      fullPath: '/tamanho-real'
      preLoaderRoute: typeof TamanhoRealRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/primeira-consulta': {
      id: '/primeira-consulta'
      path: '/primeira-consulta'
      fullPath: '/primeira-consulta'
      preLoaderRoute: typeof PrimeiraConsultaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mural': {
      id: '/mural'
      path: '/mural'
      fullPath: '/mural'
      preLoaderRoute: typeof MuralRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modo-acompanhante': {
      id: '/modo-acompanhante'
      path: '/modo-acompanhante'
      fullPath: '/modo-acompanhante'
      preLoaderRoute: typeof ModoAcompanhanteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mitos': {
      id: '/mitos'
      path: '/mitos'
      fullPath: '/mitos'
      preLoaderRoute: typeof MitosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/medicos': {
      id: '/medicos'
      path: '/medicos'
      fullPath: '/medicos'
      preLoaderRoute: typeof MedicosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lives': {
      id: '/lives'
      path: '/lives'
      fullPath: '/lives'
      preLoaderRoute: typeof LivesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hospitais': {
      id: '/hospitais'
      path: '/hospitais'
      fullPath: '/hospitais'
      preLoaderRoute: typeof HospitaisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gestacao': {
      id: '/gestacao'
      path: '/gestacao'
      fullPath: '/gestacao'
      preLoaderRoute: typeof GestacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/epds': {
      id: '/epds'
      path: '/epds'
      fullPath: '/epds'
      preLoaderRoute: typeof EpdsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/empresas': {
      id: '/empresas'
      path: '/empresas'
      fullPath: '/empresas'
      preLoaderRoute: typeof EmpresasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dpp': {
      id: '/dpp'
      path: '/dpp'
      fullPath: '/dpp'
      preLoaderRoute: typeof DppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diabetes-gestacional': {
      id: '/diabetes-gestacional'
      path: '/diabetes-gestacional'
      fullPath: '/diabetes-gestacional'
      preLoaderRoute: typeof DiabetesGestacionalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/depoimentos': {
      id: '/depoimentos'
      path: '/depoimentos'
      fullPath: '/depoimentos'
      preLoaderRoute: typeof DepoimentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cards': {
      id: '/cards'
      path: '/cards'
      fullPath: '/cards'
      preLoaderRoute: typeof CardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculadora': {
      id: '/calculadora'
      path: '/calculadora'
      fullPath: '/calculadora'
      preLoaderRoute: typeof CalculadoraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/batimentos': {
      id: '/batimentos'
      path: '/batimentos'
      fullPath: '/batimentos'
      preLoaderRoute: typeof BatimentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bastidores': {
      id: '/bastidores'
      path: '/bastidores'
      fullPath: '/bastidores'
      preLoaderRoute: typeof BastidoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agendamento': {
      id: '/agendamento'
      path: '/agendamento'
      fullPath: '/agendamento'
      preLoaderRoute: typeof AgendamentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acompanhante': {
      id: '/acompanhante'
      path: '/acompanhante'
      fullPath: '/acompanhante'
      preLoaderRoute: typeof AcompanhanteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/votar-nome/$token': {
      id: '/votar-nome/$token'
      path: '/votar-nome/$token'
      fullPath: '/votar-nome/$token'
      preLoaderRoute: typeof VotarNomeTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/medicos_/cadastro': {
      id: '/medicos_/cadastro'
      path: '/medicos/cadastro'
      fullPath: '/medicos/cadastro'
      preLoaderRoute: typeof MedicosCadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/whatsapp': {
      id: '/api/whatsapp'
      path: '/api/whatsapp'
      fullPath: '/api/whatsapp'
      preLoaderRoute: typeof ApiWhatsappRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/transcribe': {
      id: '/api/transcribe'
      path: '/api/transcribe'
      fullPath: '/api/transcribe'
      preLoaderRoute: typeof ApiTranscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/nutrition': {
      id: '/api/nutrition'
      path: '/api/nutrition'
      fullPath: '/api/nutrition'
      preLoaderRoute: typeof ApiNutritionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/carta-semanal': {
      id: '/api/carta-semanal'
      path: '/api/carta-semanal'
      fullPath: '/api/carta-semanal'
      preLoaderRoute: typeof ApiCartaSemanalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/album/$token': {
      id: '/album/$token'
      path: '/album/$token'
      fullPath: '/album/$token'
      preLoaderRoute: typeof AlbumTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acompanhar/$token': {
      id: '/acompanhar/$token'
      path: '/acompanhar/$token'
      fullPath: '/acompanhar/$token'
      preLoaderRoute: typeof AcompanharTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/painel': {
      id: '/_authenticated/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof AuthenticatedPainelRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/minha-conta': {
      id: '/_authenticated/minha-conta'
      path: '/minha-conta'
      fullPath: '/minha-conta'
      preLoaderRoute: typeof AuthenticatedMinhaContaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedMinhaContaRoute: typeof AuthenticatedMinhaContaRoute
  AuthenticatedPainelRoute: typeof AuthenticatedPainelRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedMinhaContaRoute: AuthenticatedMinhaContaRoute,
  AuthenticatedPainelRoute: AuthenticatedPainelRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AcompanhanteRoute: AcompanhanteRoute,
  AgendamentoRoute: AgendamentoRoute,
  AuthRoute: AuthRoute,
  BastidoresRoute: BastidoresRoute,
  BatimentosRoute: BatimentosRoute,
  CalculadoraRoute: CalculadoraRoute,
  CardsRoute: CardsRoute,
  DepoimentosRoute: DepoimentosRoute,
  DiabetesGestacionalRoute: DiabetesGestacionalRoute,
  DppRoute: DppRoute,
  EmpresasRoute: EmpresasRoute,
  EpdsRoute: EpdsRoute,
  GestacaoRoute: GestacaoRoute,
  HospitaisRoute: HospitaisRoute,
  LivesRoute: LivesRoute,
  MedicosRoute: MedicosRoute,
  MitosRoute: MitosRoute,
  ModoAcompanhanteRoute: ModoAcompanhanteRoute,
  MuralRoute: MuralRoute,
  PrimeiraConsultaRoute: PrimeiraConsultaRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SobreRoute: SobreRoute,
  TamanhoRealRoute: TamanhoRealRoute,
  AcompanharTokenRoute: AcompanharTokenRoute,
  AlbumTokenRoute: AlbumTokenRoute,
  ApiCartaSemanalRoute: ApiCartaSemanalRoute,
  ApiChatRoute: ApiChatRoute,
  ApiNutritionRoute: ApiNutritionRoute,
  ApiTranscribeRoute: ApiTranscribeRoute,
  ApiWhatsappRoute: ApiWhatsappRoute,
  MedicosCadastroRoute: MedicosCadastroRoute,
  VotarNomeTokenRoute: VotarNomeTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
